NeverFoundry.Wiki.Sample/MVC/Pages/AdminPortal.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NeverFoundry.Wiki.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace NeverFoundry.Wiki.MVCSample.Pages
{
    [Authorize(Policy = Constants.Claim_WikiAdmin)]
    public class AdminPortalModel : PageModel
    {
        private readonly UserManager<WikiUser> _userManager;

        public int CurrentPage { get; set; }

        [TempData] public string? ErrorMessage { get; set; }

        [BindProperty] public InputModel Input { get; set; } = new InputModel();

        public bool IsSiteAdmin { get; set; }

        public int ItemsPerPage { get; set; }

        public long PageCount { get; set; }

        [TempData] public string? StatusMessage { get; set; }

        public long UserCountActive { get; set; }

        public long UserCountDeleted { get; set; }

        public long UserCountDisabled { get; set; }

        public long UserCountInactive { get; set; }

        public long UserCountTotal { get; set; }

        public List<UserWithClaims>? Users { get; set; }

        public class UserWithClaims
        {
            public IList<Claim> Claims { get; set; } = new List<Claim>();

            public WikiUser User { get; }

            public UserWithClaims(WikiUser user) => User = user;
        }

        public class InputModel
        {
            [Required] public string? Id { get; set; }
        }

        public AdminPortalModel(UserManager<WikiUser> userManager) => _userManager = userManager;

        public async Task<IActionResult> OnGetAsync(int page = 1, int count = 25)
        {
            var result = await VerifyAdminAsync().ConfigureAwait(false);
            if (result != null)
            {
                return result;
            }

            CurrentPage = page;
            ItemsPerPage = count;

            UserCountActive = _userManager.Users.LongCount(x => !x.IsDeleted && !x.IsDisabled && x.LastAccess.AddYears(1) >= DateTimeOffset.UtcNow);
            UserCountDeleted = _userManager.Users.LongCount(x => x.IsDeleted);
            UserCountDisabled = _userManager.Users.LongCount(x => x.IsDisabled);
            UserCountInactive = _userManager.Users.LongCount(x => !x.IsDeleted && !x.IsDisabled && x.LastAccess.AddYears(1) < DateTimeOffset.UtcNow);
            UserCountTotal = _userManager.Users.LongCount();

            PageCount = UserCountTotal / ItemsPerPage;
            if (UserCountTotal % ItemsPerPage != 0)
            {
                PageCount++;
            }

            Users = _userManager.Users
                .OrderBy(x => x.UserName)
                .Skip((CurrentPage - 1) * ItemsPerPage)
                .Take(ItemsPerPage)
                .Select(x => new UserWithClaims(x))
                .ToList();
            foreach (var user in Users)
            {
                user.Claims = await _userManager.GetClaimsAsync(user.User).ConfigureAwait(false);
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAddWikiAdminAsync()
        {
            var result = await VerifyAdminAsync().ConfigureAwait(false);
            if (result != null)
            {
                return result;
            }

            if (!ModelState.IsValid)
            {
                ErrorMessage = "An error occurred. Please refresh the page and try again.";
                return RedirectToPage();
            }

            var user = await _userManager.FindByIdAsync(Input.Id).ConfigureAwait(false);
            if (user is null)
            {
                ErrorMessage = "An error occurred. Please refresh the page and try again.";
                return RedirectToPage();
            }
            var identityResult = await _userManager.AddClaimAsync(user, new Claim(Constants.Claim_WikiAdmin, true.ToString(), ClaimValueTypes.Boolean)).ConfigureAwait(false);
            if (!identityResult.Succeeded)
            {
                ErrorMessage = "An error occurred. Please refresh the page and try again.";
                return RedirectToPage();
            }

            StatusMessage = "User has been made an admin";
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostDisableUserAsync()
        {
            var result = await VerifyAdminAsync().ConfigureAwait(false);
            if (result != null)
            {
                return result;
            }

            if (!ModelState.IsValid)
            {
                ErrorMessage = "An error occurred. Please refresh the page and try again.";
                return RedirectToPage();
            }

            var user = await _userManager.FindByIdAsync(Input.Id).ConfigureAwait(false);
            if (user is null)
            {
                ErrorMessage = "An error occurred. Please refresh the page and try again.";
                return RedirectToPage();
            }

            user.IsDisabled = true;
            user.DisabledStart = DateTimeOffset.UtcNow;
            var identityResult = await _userManager.UpdateAsync(user).ConfigureAwait(false);
            if (!identityResult.Succeeded)
            {
                ErrorMessage = "An error occurred. Please refresh the page and try again.";
                return RedirectToPage();
            }

            StatusMessage = "User has been disabled";
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostEnableUserAsync()
        {
            var result = await VerifyAdminAsync().ConfigureAwait(false);
            if (result != null)
            {
                return result;
            }

            if (!ModelState.IsValid)
            {
                ErrorMessage = "An error occurred. Please refresh the page and try again.";
                return RedirectToPage();
            }

            var user = await _userManager.FindByIdAsync(Input.Id).ConfigureAwait(false);
            if (user is null)
            {
                ErrorMessage = "An error occurred. Please refresh the page and try again.";
                return RedirectToPage();
            }

            user.IsDisabled = false;
            user.DisabledStart = null;
            var identityResult = await _userManager.UpdateAsync(user).ConfigureAwait(false);
            if (!identityResult.Succeeded)
            {
                ErrorMessage = "An error occurred. Please refresh the page and try again.";
                return RedirectToPage();
            }

            StatusMessage = "User has been enabled";
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRemoveWikiAdminAsync()
        {
            var result = await VerifyAdminAsync().ConfigureAwait(false);
            if (result != null)
            {
                return result;
            }

            if (!ModelState.IsValid)
            {
                ErrorMessage = "An error occurred. Please refresh the page and try again.";
                return RedirectToPage();
            }

            var user = await _userManager.FindByIdAsync(Input.Id).ConfigureAwait(false);
            if (user is null)
            {
                ErrorMessage = "An error occurred. Please refresh the page and try again.";
                return RedirectToPage();
            }

            var claims = await _userManager.GetClaimsAsync(user).ConfigureAwait(false);
            claims = claims.Where(x => x.Type == Constants.Claim_WikiAdmin).ToList();
            var identityResult = await _userManager.RemoveClaimsAsync(user, claims).ConfigureAwait(false);
            if (!identityResult.Succeeded)
            {
                ErrorMessage = "An error occurred. Please refresh the page and try again.";
                return RedirectToPage();
            }

            StatusMessage = "User is no longer an admin";
            return RedirectToPage();
        }

        private async Task<IActionResult?> VerifyAdminAsync()
        {
            var user = await _userManager.GetUserAsync(User).ConfigureAwait(false);
            if (user is null)
            {
                return RedirectToPage("/Account/Login");
            }

            var claims = await _userManager.GetClaimsAsync(user).ConfigureAwait(false);
            if (!claims.HasBoolClaim(Constants.Claim_WikiAdmin))
            {
                return Unauthorized();
            }

            return null;
        }
    }
}

NeverFoundry.Wiki.Sample/MVC/Pages/AdminPortal.cshtml
@page
@model NeverFoundry.Wiki.MVCSample.Pages.AdminPortalModel

@inject UserManager<WikiUser> UserManager

@{
    ViewData["Title"] = "Admin";
}

<div class="jumbotron jumbotron-fluid">
    <div class="container d-flex flex-column">
        <h1 class="display-4">@ViewData["Title"]</h1>
        <p class="lead">There are currently <strong class="text-primary">@Model.UserCountTotal.ToString("N0")</strong> total registered users.</p>
        <div class="container-fluid ml-1">
            <div class="row justify-content-center">
                <div class="col-2">Active users:</div>
                <div class="col-1"><strong class="text-success">@Model.UserCountActive.ToString("N0")</strong></div>
            </div>
            <div class="row justify-content-center">
                <div class="col-2">Inactive users:</div>
                <div class="col-1"><strong class="text-muted">@Model.UserCountInactive.ToString("N0")</strong></div>
            </div>
            <div class="row justify-content-center">
                <div class="col-2">Disabled users:</div>
                <div class="col-1"><strong class="text-warning">@Model.UserCountDisabled.ToString("N0")</strong></div>
            </div>
            <div class="row justify-content-center">
                <div class="col-2">Deleted users:</div>
                <div class="col-1"><strong class="text-danger">@Model.UserCountDeleted.ToString("N0")</strong></div>
            </div>
        </div>
    </div>
</div>
<partial name="_ErrorMessage" for="ErrorMessage" />
<partial name="_StatusMessage" for="StatusMessage" />
@if ((Model.Users?.Count ?? 0) > 0)
{
    <div class="row justify-content-center mb-3">
        <div class="col-sm-10">
            <ul class="list-group d-flex flex-wrap">
                @foreach (var user in Model.Users!)
                {
                    <li class="list-group-item">
                        <div class="container-fluid">
                            <div class="row align-items-center">
                                <div class="col-auto d-flex align-items-start">
                                    <h5 class="mb-1 @(user.User.LastAccess.AddYears(1) < DateTimeOffset.UtcNow ? "text-muted" : string.Empty)">@user.User.UserName</h5>
                                    @if (user.Claims.HasBoolClaim(Constants.Claim_SiteAdmin))
                                    {
                                        <span class="badge badge-pill badge-primary">
                                            <i class="material-icons">star</i>
                                            <span class="sr-only">site admin</span>
                                        </span>
                                    }
                                    else if (Model.IsSiteAdmin)
                                    {
                                        if (user.Claims.HasBoolClaim(Constants.Claim_WikiAdmin))
                                        {
                                            @if (user.Claims.HasBoolClaim(Constants.Claim_SiteAdmin))
                                            {
                                                <form method="post" asp-page-handler="RemoveWikiAdmin" style="display: inline-block">
                                                    <input type="hidden" value="@user.User.Id" />
                                                    <button type="submit" class="btn btn-warning" title="Wiki admin (click to remove)">
                                                        <i class="material-icons">star</i>
                                                        <span class="sr-only">is a wiki admin</span>
                                                    </button>
                                                </form>
                                            }
                                            else
                                            {
                                                <span class="badge badge-pill badge-warning" title="Wiki admin">
                                                    <i class="material-icons">star</i>
                                                    <span class="sr-only">is a wiki admin</span>
                                                </span>
                                            }
                                        }
                                        else if (!user.User.IsDeleted)
                                        {
                                            @if (user.Claims.HasBoolClaim(Constants.Claim_SiteAdmin))
                                            {
                                                <form method="post" asp-page-handler="AddWikiAdmin" style="display: inline-block">
                                                    <input type="hidden" value="@user.User.Id" />
                                                    <button type="submit" class="btn btn-light" title="Not a wiki admin (click to add)">
                                                        <i class="material-icons">star</i>
                                                        <span class="sr-only">not a wiki admin</span>
                                                    </button>
                                                </form>
                                            }
                                            else
                                            {
                                                <span class="badge badge-pill badge-light" title="Not a wiki admin">
                                                    <i class="material-icons">star</i>
                                                    <span class="sr-only">not a wiki admin</span>
                                                </span>
                                            }
                                        }
                                    }
                                </div>
                                <div class="col-auto d-flex">
                                    @user.User.Email @if (user.User.EmailConfirmed)
                                    {<span class="text-success">✓</span>}
                                </div>
                                <div class="col-auto mr-auto">
                                    @if (user.User.LastAccess.AddYears(1) < DateTimeOffset.UtcNow)
                                    {
                                        <small class="text-muted">Last access: @(user.User.LastAccess == DateTime.MinValue ? "Never" : user.User.LastAccess.ToString("Y"))</small>
                                    }
                                </div>
                                @if (!user.User.IsDeleted)
                                {
                                    <div class="col-auto">
                                        @if (user.User.IsDisabled)
                                        {
                                            <form method="post" asp-page-handler="EnableUser" style="display: inline-block">
                                                <input type="hidden" value="@user.User.Id" />
                                                <span class="text-danger">Account disabled</span>
                                                <button type="submit" class="btn btn-outline-danger">Enable</button>
                                            </form>
                                        }
                                        else if (user.Claims.HasBoolClaim(Constants.Claim_SiteAdmin) != true
                                            && user.Claims.HasBoolClaim(Constants.Claim_WikiAdmin) != true)
                                        {
                                            <form method="post" asp-page-handler="DisableUser" style="display: inline-block">
                                                <input type="hidden" value="@user.User.Id" />
                                                <button type="submit" class="btn btn-danger">Disable</button>
                                            </form>
                                        }
                                    </div>
                                }
                                <div class="col-auto">
                                    @if (user.User.IsDeleted)
                                    {
                                        <span class="text-danger">Account deleted</span>
                                    }
                                    else if (user.Claims.HasBoolClaim(Constants.Claim_SiteAdmin) != true
                                        && user.Claims.HasBoolClaim(Constants.Claim_WikiAdmin) != true)
                                    {
                                        <a class="btn btn-danger" asp-page="./Account/ConfirmAdminDelete" asp-route-userId="@user.User.Id">
                                            Delete <i class="material-icons">warning</i>
                                        </a>
                                    }
                                </div>
                            </div>
                        </div>
                    </li>
                }
            </ul>
        </div>
    </div>
}
<div class="row justify-content-center mb-3">
    <div class="col-sm-10">
        <nav>
            <ul class="pagination justify-content-center">
                <li class="page-item @(Model.CurrentPage == 0 ? "disabled" : string.Empty)">
                    <a class="page-link" asp-page="./AdminPortal" asp-route-page="@(Model.CurrentPage - 1)" asp-route-count="@Model.ItemsPerPage" aria-label="Previous" aria-disabled="@(Model.CurrentPage == 0)">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                @if (Model.PageCount > 5 && Model.CurrentPage > 3)
                {
                    <li class="page-item">
                        <a class="page-link" asp-page="./AdminPortal" asp-route-page="@(Model.CurrentPage - 5)" asp-route-count="@Model.ItemsPerPage">&hellip;</a>
                    </li>
                }
                @for (var i = Math.Max(0L, Model.CurrentPage - 2); i < Math.Min(Model.PageCount - 1, Model.CurrentPage + 2); i++)
                {
                    @if (Model.CurrentPage == i)
                    {
                        <li class="page-item active">
                            <a class="page-link" href="#" aria-disabled="true">@i <span class="sr-only">(current)</span></a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item">
                            <a class="page-link" asp-page="./AdminPortal" asp-route-page="@i" asp-route-count="@Model.ItemsPerPage">@i</a>
                        </li>
                    }
                }
                @if (Model.PageCount > 5 && Model.CurrentPage < Model.PageCount - 3)
                {
                    <li class="page-item">
                        <a class="page-link" asp-page="./AdminPortal" asp-route-page="@(Model.CurrentPage + 5)" asp-route-count="@Model.ItemsPerPage">&hellip;</a>
                    </li>
                }
                <li class="page-item @(Model.CurrentPage == Model.PageCount ? "disabled" : string.Empty)">
                    <a class="page-link" asp-page="./AdminPortal" asp-route-page="@(Model.CurrentPage + 1)" asp-route-count="@Model.ItemsPerPage" aria-label="Next" aria-disabled="@(Model.CurrentPage == Model.PageCount)">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>